# Generated by Django 6.0.4 on 2026-04-21 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="article_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="article_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
