# Generated by Django 6.0.4 on 2026-04-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_dislikes_article_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="article",
            name="likes",
        ),
    ]
