# Generated by Django 6.0.4 on 2026-04-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_comment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="date",
        ),
    ]
