# Generated by Django 6.0.4 on 2026-04-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_remove_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="comment",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
